### ISSUE TITLE
events/facts matching with non-literals strings

### ISSUE THREAD

**Issue by alialkhalidi** [ansible/ansible-rulebook#471]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Bug Summary

trying to figure how to parameterise a condition with the following rulebook, except that the commented line results in no match of the condition:

```
.
├── hosts.yml
├── local_copy.yml
├── playbook-create.yml
├── playbook-delete.yml
└── webhooks.yml
```
hosts.yml
```
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
```
local_copy.yml
```
resource_list: []
```

playbook-create.yml
```
---
- hosts: local
  gather_facts: false
  vars:
    local_copy_file: "/tmp/local_copy.yml"
  tasks:
    - ansible.builtin.stat:
        path: "{{ local_copy_file }}"
      register: local_copy_stat

    - ansible.builtin.copy:
        dest: "{{ local_copy_file }}"
        content: "resource_list: []"
      when: local_copy_stat.stat.exists == false

    - ansible.builtin.include_vars:
        file: "{{ local_copy_file }}"
        name: observed

    - set_fact:
        cacheable: true
        active:
          resource_list: "{{ observed.resource_list + [ansible_eda.event.payload.resource_name] }}"

    - copy:
        dest: "{{ local_copy_file }}"
        content: "resource_list: {{ active.resource_list }}"
```

playbook-delete.yml
```
---
- hosts: local
  gather_facts: false
  vars:
    local_copy_file: "/tmp/local_copy.yml"
  tasks:
    - ansible.builtin.include_vars:
        file: "{{ local_copy_file }}"
        name: observed
    - set_fact:
        cacheable: true
        active:
          resource_list: "{{ observed.resource_list | difference([ansible_eda.events.m_0.payload.resource_name]) }}"
    - copy:
        dest: "{{ local_copy_file }}"
        content: "resource_list: {{ active.resource_list }}"
```
webhooks.yml
```
---
- name: Ruleset 1
  hosts: all
  sources:   
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Inspect Create request
      condition: >
        event.payload.event_name == "Create"
      action:
        run_playbook:
          name: playbook-create.yml
          post_events: true
          set_facts: true
    - name: Post Create request
      condition:
        all:
          - events.scoped << event.active.resource_list is defined
      action:
        post_event:
          ruleset: Ruleset 2
          event:
            payload:
              resource_list: "{{ events.scoped.active.resource_list }}"

- name: Ruleset 2
  hosts: all
  sources:   
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Process Delete
      condition:
        all:
          - event.payload.event_name == "Delete"
          - event.payload.resource_list is select("search", "r1")
#          - event.payload.resource_list is select("search", events.m_0.payload.resource_name)
      action:
        run_playbook:
          name: playbook-delete.yml
```

### Environment

```
__version__ = '0.11.0'
  Executable location = /home/alialkhalidi/work/ansible-04062023/bin/ansible-rulebook
  Drools_jpy version = 0.2.8
  Java home = /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc36.x86_64/
  Java version = 17.0.6
  Python version = 3.10.10 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
```

### Steps to reproduce

1- run the rulebook with: ``` ansible-rulebook --rulebook webhooks.yml -i hosts.yml  -v ```
2- run a call with: ```  curl -d '{"event_name":"Create","resource_name":"r1"}' localhost:5000 ```
3- run a call with: ```  curl -d '{"event_name":"Delete","resource_name":"r1"}' localhost:5001 ```
4- local_copy.yml will have active_list: []

### Actual results

- un-comment the line, and repeat steps 1-4, the condition for Ruleset 2 does not match, and playbook-delete.yml does not get triggered.

### Expected results

the condition for Ruleset 2 matches, and playbook-delete.yml gets triggered.

### Additional information

ansible-rulebook is from current tip main.
