### ISSUE TITLE
EDA Credential Objects

### ISSUE THREAD

**Issue by Bri2785** [ansible/ansible-rulebook#570]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

In the current version of AAP, we have credential objects to leverage to pass in sensitive values to the playbook. In EDA, when leveraging the webhook plugin (and possibly others), securing this endpoint currently requires a plain text token committed to the code base. A credential object being available that was injected at runtime would alleviate this.

### Steps to reproduce

Create a rulebook using any source plugin requiring a sensitive parameter
``` 
hosts: localhost
sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
      token: MySecretToken

### Current results

The parameter needs to be committed in plain text

### Sugested feature result

The ability to inject the sensitive value at runtime
```
hosts: localhost
sources:
  - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
      token: {{ token }}
